services:
  ragflow:
    image: infiniflow/ragflow:${RAGFLOW_VERSION:-latest}
    platform: linux/amd64
    container_name: ragflow-nas
    restart: unless-stopped
    env_file: .env
    environment:
      # Database (MySQL local)
      - DB_TYPE=mysql
      - DATABASE_TYPE=mysql
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=ai_lab_ragflow_admin
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=ai_lab_ragflow
      - MYSQL_DBNAME=ai_lab_ragflow
      # MinIO (local)
      - MINIO_HOST=minio
      - MINIO_PORT=9000
      - MINIO_USER=${MINIO_ROOT_USER}
      - MINIO_PASSWORD=${MINIO_ROOT_PASSWORD}
      # Redis (local)
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      # Elasticsearch (local)
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      # Task Executor
      - EXECUTOR_WORKERS=6
    volumes:
      - ${RAGFLOW_DATA_PATH}:/ragflow/data
      - ${RAGFLOW_LOG_PATH}:/ragflow/logs
      - ./nginx-ragflow-fixed.conf:/etc/nginx/sites-available/ragflow:ro
      - ./entrypoint-wrapper.sh:/entrypoint-wrapper.sh:ro
      - ./conf/service_conf.yaml.template:/ragflow/conf/service_conf.yaml.template:ro
    entrypoint: ["/bin/bash", "/entrypoint-wrapper.sh"]
    ports:
      - "0.0.0.0:${RAGFLOW_PORT}:80"  # Changed to port 80 for nginx
      - "0.0.0.0:9382:9382"  # MCP server port
    depends_on:
      - elasticsearch
      - minio
      - redis
      - mysql
    networks:
      - npm-network
      - ragflow-internal

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: ragflow-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - xpack.security.enrollment.enabled=false
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9201:9200"  # Local access only
    networks:
      - ragflow-internal
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  mysql:
    image: mysql:8.0
    container_name: ragflow-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-mysqlroot123}
      - MYSQL_DATABASE=ai_lab_ragflow
      - MYSQL_USER=ai_lab_ragflow_admin
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - ragflow-internal
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  minio:
    image: minio/minio:latest
    container_name: ragflow-minio-nas
    restart: unless-stopped
    command: server /data --console-address ":${MINIO_PORT}"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./minio:/data
    ports:
      - "9000:9000"
      - "${MINIO_PORT}:${MINIO_PORT}"
    networks:
      - ragflow-internal

  redis:
    image: redis:8
    container_name: ragflow-redis-nas
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./redis:/data
    networks:
      - ragflow-internal

networks:
  npm-network:
    external: true
  ragflow-internal:
    driver: bridge